//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eWarranty.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("eWarranty.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        internal static string lblBack {
            get {
                return ResourceManager.GetString("lblBack", resourceCulture);
            }
        }
        
        internal static string lblNext {
            get {
                return ResourceManager.GetString("lblNext", resourceCulture);
            }
        }
        
        internal static string lblSubmit {
            get {
                return ResourceManager.GetString("lblSubmit", resourceCulture);
            }
        }
        
        internal static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        internal static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        internal static string lblSignin {
            get {
                return ResourceManager.GetString("lblSignin", resourceCulture);
            }
        }
        
        internal static string lblSignUp {
            get {
                return ResourceManager.GetString("lblSignUp", resourceCulture);
            }
        }
        
        internal static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        internal static string lblForgotPassword {
            get {
                return ResourceManager.GetString("lblForgotPassword", resourceCulture);
            }
        }
        
        internal static string lbltitelForgotPassword {
            get {
                return ResourceManager.GetString("lbltitelForgotPassword", resourceCulture);
            }
        }
        
        internal static string lblMsgEmailErrorForgotPassword {
            get {
                return ResourceManager.GetString("lblMsgEmailErrorForgotPassword", resourceCulture);
            }
        }
        
        internal static string lblMsgEmailValidErrorForgotPassword {
            get {
                return ResourceManager.GetString("lblMsgEmailValidErrorForgotPassword", resourceCulture);
            }
        }
        
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        internal static string lblContactNumber {
            get {
                return ResourceManager.GetString("lblContactNumber", resourceCulture);
            }
        }
        
        internal static string lblErrorName {
            get {
                return ResourceManager.GetString("lblErrorName", resourceCulture);
            }
        }
        
        internal static string lblErrorEmail {
            get {
                return ResourceManager.GetString("lblErrorEmail", resourceCulture);
            }
        }
        
        internal static string lblErrorValidEmail {
            get {
                return ResourceManager.GetString("lblErrorValidEmail", resourceCulture);
            }
        }
        
        internal static string lblErrorContactNumber {
            get {
                return ResourceManager.GetString("lblErrorContactNumber", resourceCulture);
            }
        }
        
        internal static string lblErrorTitle {
            get {
                return ResourceManager.GetString("lblErrorTitle", resourceCulture);
            }
        }
        
        internal static string lblOk {
            get {
                return ResourceManager.GetString("lblOk", resourceCulture);
            }
        }
        
        internal static string inquery {
            get {
                return ResourceManager.GetString("inquery", resourceCulture);
            }
        }
        
        internal static string servererror {
            get {
                return ResourceManager.GetString("servererror", resourceCulture);
            }
        }
        
        internal static string lblValidMobileNo {
            get {
                return ResourceManager.GetString("lblValidMobileNo", resourceCulture);
            }
        }
        
        internal static string titlePanasonicSmartCare {
            get {
                return ResourceManager.GetString("titlePanasonicSmartCare", resourceCulture);
            }
        }
        
        internal static string btnMyProducts {
            get {
                return ResourceManager.GetString("btnMyProducts", resourceCulture);
            }
        }
        
        internal static string btnRegisterProduct {
            get {
                return ResourceManager.GetString("btnRegisterProduct", resourceCulture);
            }
        }
        
        internal static string btnTrackService {
            get {
                return ResourceManager.GetString("btnTrackService", resourceCulture);
            }
        }
        
        internal static string btnServiceCenter {
            get {
                return ResourceManager.GetString("btnServiceCenter", resourceCulture);
            }
        }
        
        internal static string btnSmartAssistant {
            get {
                return ResourceManager.GetString("btnSmartAssistant", resourceCulture);
            }
        }
        
        internal static string btnHome {
            get {
                return ResourceManager.GetString("btnHome", resourceCulture);
            }
        }
        
        internal static string btnPromotion {
            get {
                return ResourceManager.GetString("btnPromotion", resourceCulture);
            }
        }
        
        internal static string btnSurvey {
            get {
                return ResourceManager.GetString("btnSurvey", resourceCulture);
            }
        }
        
        internal static string btnAccessories {
            get {
                return ResourceManager.GetString("btnAccessories", resourceCulture);
            }
        }
        
        internal static string btnSettings {
            get {
                return ResourceManager.GetString("btnSettings", resourceCulture);
            }
        }
        
        internal static string btnAssignedJobs {
            get {
                return ResourceManager.GetString("btnAssignedJobs", resourceCulture);
            }
        }
        
        internal static string titlePendingJobs {
            get {
                return ResourceManager.GetString("titlePendingJobs", resourceCulture);
            }
        }
        
        internal static string menuMyJobs {
            get {
                return ResourceManager.GetString("menuMyJobs", resourceCulture);
            }
        }
        
        internal static string menuPartRequests {
            get {
                return ResourceManager.GetString("menuPartRequests", resourceCulture);
            }
        }
        
        internal static string menuPartStock {
            get {
                return ResourceManager.GetString("menuPartStock", resourceCulture);
            }
        }
        
        internal static string menuChat {
            get {
                return ResourceManager.GetString("menuChat", resourceCulture);
            }
        }
        
        internal static string menuServiceManuals {
            get {
                return ResourceManager.GetString("menuServiceManuals", resourceCulture);
            }
        }
        
        internal static string menuTips {
            get {
                return ResourceManager.GetString("menuTips", resourceCulture);
            }
        }
        
        internal static string menuFAQ {
            get {
                return ResourceManager.GetString("menuFAQ", resourceCulture);
            }
        }
        
        internal static string menuMyQueries {
            get {
                return ResourceManager.GetString("menuMyQueries", resourceCulture);
            }
        }
        
        internal static string menuMyOrders {
            get {
                return ResourceManager.GetString("menuMyOrders", resourceCulture);
            }
        }
        
        internal static string menuProducts {
            get {
                return ResourceManager.GetString("menuProducts", resourceCulture);
            }
        }
        
        internal static string menuServicesHistory {
            get {
                return ResourceManager.GetString("menuServicesHistory", resourceCulture);
            }
        }
        
        internal static string menuChatHistory {
            get {
                return ResourceManager.GetString("menuChatHistory", resourceCulture);
            }
        }
        
        internal static string menuSurvey {
            get {
                return ResourceManager.GetString("menuSurvey", resourceCulture);
            }
        }
        
        internal static string menuTermsandConditions {
            get {
                return ResourceManager.GetString("menuTermsandConditions", resourceCulture);
            }
        }
        
        internal static string menuServiceCenter {
            get {
                return ResourceManager.GetString("menuServiceCenter", resourceCulture);
            }
        }
        
        internal static string menuMyAccount {
            get {
                return ResourceManager.GetString("menuMyAccount", resourceCulture);
            }
        }
        
        internal static string menuLogout {
            get {
                return ResourceManager.GetString("menuLogout", resourceCulture);
            }
        }
        
        internal static string menuBuyAMC {
            get {
                return ResourceManager.GetString("menuBuyAMC", resourceCulture);
            }
        }
        
        internal static string titleProducts {
            get {
                return ResourceManager.GetString("titleProducts", resourceCulture);
            }
        }
        
        internal static string plcSearchModelNumber {
            get {
                return ResourceManager.GetString("plcSearchModelNumber", resourceCulture);
            }
        }
        
        internal static string lblNoProducts {
            get {
                return ResourceManager.GetString("lblNoProducts", resourceCulture);
            }
        }
        
        internal static string lblModelNo {
            get {
                return ResourceManager.GetString("lblModelNo", resourceCulture);
            }
        }
        
        internal static string lblSerialNo {
            get {
                return ResourceManager.GetString("lblSerialNo", resourceCulture);
            }
        }
        
        internal static string lblWarranty {
            get {
                return ResourceManager.GetString("lblWarranty", resourceCulture);
            }
        }
        
        internal static string lblExpiresIn {
            get {
                return ResourceManager.GetString("lblExpiresIn", resourceCulture);
            }
        }
        
        internal static string btnDetails {
            get {
                return ResourceManager.GetString("btnDetails", resourceCulture);
            }
        }
        
        internal static string lblNearByServiceCenters {
            get {
                return ResourceManager.GetString("lblNearByServiceCenters", resourceCulture);
            }
        }
        
        internal static string plcFindLocation {
            get {
                return ResourceManager.GetString("plcFindLocation", resourceCulture);
            }
        }
        
        internal static string lblLandmark {
            get {
                return ResourceManager.GetString("lblLandmark", resourceCulture);
            }
        }
        
        internal static string lblCityName {
            get {
                return ResourceManager.GetString("lblCityName", resourceCulture);
            }
        }
        
        internal static string lblWorkingHours {
            get {
                return ResourceManager.GetString("lblWorkingHours", resourceCulture);
            }
        }
        
        internal static string lblDistnace {
            get {
                return ResourceManager.GetString("lblDistnace", resourceCulture);
            }
        }
        
        internal static string lblLocatewithin50kilometers {
            get {
                return ResourceManager.GetString("lblLocatewithin50kilometers", resourceCulture);
            }
        }
        
        internal static string titleProductDetails {
            get {
                return ResourceManager.GetString("titleProductDetails", resourceCulture);
            }
        }
        
        internal static string lblPurchasedon {
            get {
                return ResourceManager.GetString("lblPurchasedon", resourceCulture);
            }
        }
        
        internal static string lblRegisteredon {
            get {
                return ResourceManager.GetString("lblRegisteredon", resourceCulture);
            }
        }
        
        internal static string lblWarrantyInformation {
            get {
                return ResourceManager.GetString("lblWarrantyInformation", resourceCulture);
            }
        }
        
        internal static string lblWarrantyType {
            get {
                return ResourceManager.GetString("lblWarrantyType", resourceCulture);
            }
        }
        
        internal static string lblExpiredon {
            get {
                return ResourceManager.GetString("lblExpiredon", resourceCulture);
            }
        }
        
        internal static string lblDealerInformation {
            get {
                return ResourceManager.GetString("lblDealerInformation", resourceCulture);
            }
        }
        
        internal static string lblDealerName {
            get {
                return ResourceManager.GetString("lblDealerName", resourceCulture);
            }
        }
        
        internal static string lblDealerLocation {
            get {
                return ResourceManager.GetString("lblDealerLocation", resourceCulture);
            }
        }
        
        internal static string lblCountryofpurchase {
            get {
                return ResourceManager.GetString("lblCountryofpurchase", resourceCulture);
            }
        }
        
        internal static string lblInvoiceNumber {
            get {
                return ResourceManager.GetString("lblInvoiceNumber", resourceCulture);
            }
        }
        
        internal static string btnServiceRequest {
            get {
                return ResourceManager.GetString("btnServiceRequest", resourceCulture);
            }
        }
        
        internal static string lblProductLabel {
            get {
                return ResourceManager.GetString("lblProductLabel", resourceCulture);
            }
        }
        
        internal static string lblPurchaseInvoice {
            get {
                return ResourceManager.GetString("lblPurchaseInvoice", resourceCulture);
            }
        }
        
        internal static string lblTermsandConditions {
            get {
                return ResourceManager.GetString("lblTermsandConditions", resourceCulture);
            }
        }
        
        internal static string titleRegister {
            get {
                return ResourceManager.GetString("titleRegister", resourceCulture);
            }
        }
        
        internal static string lblModelNumber {
            get {
                return ResourceManager.GetString("lblModelNumber", resourceCulture);
            }
        }
        
        internal static string plcModelNumber {
            get {
                return ResourceManager.GetString("plcModelNumber", resourceCulture);
            }
        }
        
        internal static string lblSerialNumber {
            get {
                return ResourceManager.GetString("lblSerialNumber", resourceCulture);
            }
        }
        
        internal static string plcSerialNumber {
            get {
                return ResourceManager.GetString("plcSerialNumber", resourceCulture);
            }
        }
        
        internal static string lblPurchaseDate {
            get {
                return ResourceManager.GetString("lblPurchaseDate", resourceCulture);
            }
        }
        
        internal static string plcInvoiceNumber {
            get {
                return ResourceManager.GetString("plcInvoiceNumber", resourceCulture);
            }
        }
        
        internal static string plcUploadPurchaseInvoice {
            get {
                return ResourceManager.GetString("plcUploadPurchaseInvoice", resourceCulture);
            }
        }
        
        internal static string plcUploadProductLabel {
            get {
                return ResourceManager.GetString("plcUploadProductLabel", resourceCulture);
            }
        }
        
        internal static string plcCountryofpurchase {
            get {
                return ResourceManager.GetString("plcCountryofpurchase", resourceCulture);
            }
        }
        
        internal static string lblMessage {
            get {
                return ResourceManager.GetString("lblMessage", resourceCulture);
            }
        }
        
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        internal static string lblOpenServiceRequest {
            get {
                return ResourceManager.GetString("lblOpenServiceRequest", resourceCulture);
            }
        }
        
        internal static string lblNoServiceRequest {
            get {
                return ResourceManager.GetString("lblNoServiceRequest", resourceCulture);
            }
        }
        
        internal static string lblReqNo {
            get {
                return ResourceManager.GetString("lblReqNo", resourceCulture);
            }
        }
        
        internal static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        internal static string lblRemark {
            get {
                return ResourceManager.GetString("lblRemark", resourceCulture);
            }
        }
        
        internal static string lblFeedback {
            get {
                return ResourceManager.GetString("lblFeedback", resourceCulture);
            }
        }
        
        internal static string btnFollowup {
            get {
                return ResourceManager.GetString("btnFollowup", resourceCulture);
            }
        }
        
        internal static string plcFollowupmessage {
            get {
                return ResourceManager.GetString("plcFollowupmessage", resourceCulture);
            }
        }
        
        internal static string lblProductRemarks {
            get {
                return ResourceManager.GetString("lblProductRemarks", resourceCulture);
            }
        }
        
        internal static string plcRemarks {
            get {
                return ResourceManager.GetString("plcRemarks", resourceCulture);
            }
        }
        
        internal static string lblPreferredDatetime {
            get {
                return ResourceManager.GetString("lblPreferredDatetime", resourceCulture);
            }
        }
        
        internal static string btnReschedule {
            get {
                return ResourceManager.GetString("btnReschedule", resourceCulture);
            }
        }
        
        internal static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        internal static string lblServiceCenterDetails {
            get {
                return ResourceManager.GetString("lblServiceCenterDetails", resourceCulture);
            }
        }
        
        internal static string lblAddressdetail {
            get {
                return ResourceManager.GetString("lblAddressdetail", resourceCulture);
            }
        }
        
        internal static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        internal static string lblCitynew {
            get {
                return ResourceManager.GetString("lblCitynew", resourceCulture);
            }
        }
        
        internal static string plcCity {
            get {
                return ResourceManager.GetString("plcCity", resourceCulture);
            }
        }
        
        internal static string lblAddnewproduct {
            get {
                return ResourceManager.GetString("lblAddnewproduct", resourceCulture);
            }
        }
        
        internal static string lblServiceCenterComments {
            get {
                return ResourceManager.GetString("lblServiceCenterComments", resourceCulture);
            }
        }
        
        internal static string lblSymptom {
            get {
                return ResourceManager.GetString("lblSymptom", resourceCulture);
            }
        }
        
        internal static string titleDetails {
            get {
                return ResourceManager.GetString("titleDetails", resourceCulture);
            }
        }
        
        internal static string lblRequestNo {
            get {
                return ResourceManager.GetString("lblRequestNo", resourceCulture);
            }
        }
        
        internal static string lblRequestDate {
            get {
                return ResourceManager.GetString("lblRequestDate", resourceCulture);
            }
        }
        
        internal static string lblRequestStatus {
            get {
                return ResourceManager.GetString("lblRequestStatus", resourceCulture);
            }
        }
        
        internal static string lblRequestType {
            get {
                return ResourceManager.GetString("lblRequestType", resourceCulture);
            }
        }
        
        internal static string lblProductDetails {
            get {
                return ResourceManager.GetString("lblProductDetails", resourceCulture);
            }
        }
        
        internal static string lblDealerAddress {
            get {
                return ResourceManager.GetString("lblDealerAddress", resourceCulture);
            }
        }
        
        internal static string titleFindServiceCenter {
            get {
                return ResourceManager.GetString("titleFindServiceCenter", resourceCulture);
            }
        }
        
        internal static string lblNotFound {
            get {
                return ResourceManager.GetString("lblNotFound", resourceCulture);
            }
        }
        
        internal static string titleSmartAssistant {
            get {
                return ResourceManager.GetString("titleSmartAssistant", resourceCulture);
            }
        }
        
        internal static string lblPanasonicSmartAssistant {
            get {
                return ResourceManager.GetString("lblPanasonicSmartAssistant", resourceCulture);
            }
        }
        
        internal static string lblWelcomeMessage {
            get {
                return ResourceManager.GetString("lblWelcomeMessage", resourceCulture);
            }
        }
        
        internal static string titleMyProfile {
            get {
                return ResourceManager.GetString("titleMyProfile", resourceCulture);
            }
        }
        
        internal static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        internal static string lblMobNo {
            get {
                return ResourceManager.GetString("lblMobNo", resourceCulture);
            }
        }
        
        internal static string titleUpdateProfile {
            get {
                return ResourceManager.GetString("titleUpdateProfile", resourceCulture);
            }
        }
        
        internal static string btnManageAddress {
            get {
                return ResourceManager.GetString("btnManageAddress", resourceCulture);
            }
        }
        
        internal static string btnChangePassword {
            get {
                return ResourceManager.GetString("btnChangePassword", resourceCulture);
            }
        }
        
        internal static string btnLanguage {
            get {
                return ResourceManager.GetString("btnLanguage", resourceCulture);
            }
        }
        
        internal static string btnLogout {
            get {
                return ResourceManager.GetString("btnLogout", resourceCulture);
            }
        }
        
        internal static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        internal static string lblAlternateNumber {
            get {
                return ResourceManager.GetString("lblAlternateNumber", resourceCulture);
            }
        }
        
        internal static string lblPrimaryLanguage {
            get {
                return ResourceManager.GetString("lblPrimaryLanguage", resourceCulture);
            }
        }
        
        internal static string titleAddresses {
            get {
                return ResourceManager.GetString("titleAddresses", resourceCulture);
            }
        }
        
        internal static string menuAdd {
            get {
                return ResourceManager.GetString("menuAdd", resourceCulture);
            }
        }
        
        internal static string lblStreet {
            get {
                return ResourceManager.GetString("lblStreet", resourceCulture);
            }
        }
        
        internal static string lblState {
            get {
                return ResourceManager.GetString("lblState", resourceCulture);
            }
        }
        
        internal static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        internal static string titleNewaddress {
            get {
                return ResourceManager.GetString("titleNewaddress", resourceCulture);
            }
        }
        
        internal static string plcApartment_Houseno {
            get {
                return ResourceManager.GetString("plcApartment/Houseno", resourceCulture);
            }
        }
        
        internal static string plcBuilding_Villaname {
            get {
                return ResourceManager.GetString("plcBuilding/Villaname", resourceCulture);
            }
        }
        
        internal static string plcArea {
            get {
                return ResourceManager.GetString("plcArea", resourceCulture);
            }
        }
        
        internal static string plcPostalcode {
            get {
                return ResourceManager.GetString("plcPostalcode", resourceCulture);
            }
        }
        
        internal static string opIsprimary {
            get {
                return ResourceManager.GetString("opIsprimary", resourceCulture);
            }
        }
        
        internal static string btnAddNewAddress {
            get {
                return ResourceManager.GetString("btnAddNewAddress", resourceCulture);
            }
        }
        
        internal static string titlePickyouraddress {
            get {
                return ResourceManager.GetString("titlePickyouraddress", resourceCulture);
            }
        }
        
        internal static string btnPickAddress {
            get {
                return ResourceManager.GetString("btnPickAddress", resourceCulture);
            }
        }
        
        internal static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        internal static string titleChangePassword {
            get {
                return ResourceManager.GetString("titleChangePassword", resourceCulture);
            }
        }
        
        internal static string lblCurrentPassword {
            get {
                return ResourceManager.GetString("lblCurrentPassword", resourceCulture);
            }
        }
        
        internal static string lblNewPassword {
            get {
                return ResourceManager.GetString("lblNewPassword", resourceCulture);
            }
        }
        
        internal static string lblReconfirmPassword {
            get {
                return ResourceManager.GetString("lblReconfirmPassword", resourceCulture);
            }
        }
        
        internal static string titleAccessories {
            get {
                return ResourceManager.GetString("titleAccessories", resourceCulture);
            }
        }
        
        internal static string plcSearchAccessories {
            get {
                return ResourceManager.GetString("plcSearchAccessories", resourceCulture);
            }
        }
        
        internal static string titleAccessoryDetails {
            get {
                return ResourceManager.GetString("titleAccessoryDetails", resourceCulture);
            }
        }
        
        internal static string lblDays {
            get {
                return ResourceManager.GetString("lblDays", resourceCulture);
            }
        }
        
        internal static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        internal static string btnAddtocart {
            get {
                return ResourceManager.GetString("btnAddtocart", resourceCulture);
            }
        }
        
        internal static string titleCart {
            get {
                return ResourceManager.GetString("titleCart", resourceCulture);
            }
        }
        
        internal static string btnContinue {
            get {
                return ResourceManager.GetString("btnContinue", resourceCulture);
            }
        }
        
        internal static string btnCheckout {
            get {
                return ResourceManager.GetString("btnCheckout", resourceCulture);
            }
        }
        
        internal static string lblPromoCode {
            get {
                return ResourceManager.GetString("lblPromoCode", resourceCulture);
            }
        }
        
        internal static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        internal static string lblDeliverto {
            get {
                return ResourceManager.GetString("lblDeliverto", resourceCulture);
            }
        }
        
        internal static string lblOrderSummary {
            get {
                return ResourceManager.GetString("lblOrderSummary", resourceCulture);
            }
        }
        
        internal static string lblSubTotal {
            get {
                return ResourceManager.GetString("lblSubTotal", resourceCulture);
            }
        }
        
        internal static string lbldiscount {
            get {
                return ResourceManager.GetString("lbldiscount", resourceCulture);
            }
        }
        
        internal static string lblshippingfee {
            get {
                return ResourceManager.GetString("lblshippingfee", resourceCulture);
            }
        }
        
        internal static string lblTax {
            get {
                return ResourceManager.GetString("lblTax", resourceCulture);
            }
        }
        
        internal static string lblTaxRate {
            get {
                return ResourceManager.GetString("lblTaxRate", resourceCulture);
            }
        }
        
        internal static string lblTaxDetails {
            get {
                return ResourceManager.GetString("lblTaxDetails", resourceCulture);
            }
        }
        
        internal static string lblTaxAmount {
            get {
                return ResourceManager.GetString("lblTaxAmount", resourceCulture);
            }
        }
        
        internal static string lbltotalinclusivetax {
            get {
                return ResourceManager.GetString("lbltotalinclusivetax", resourceCulture);
            }
        }
        
        internal static string lblOrderSuccessMsg {
            get {
                return ResourceManager.GetString("lblOrderSuccessMsg", resourceCulture);
            }
        }
        
        internal static string btnGotoorder {
            get {
                return ResourceManager.GetString("btnGotoorder", resourceCulture);
            }
        }
        
        internal static string lblPromocodeapplied {
            get {
                return ResourceManager.GetString("lblPromocodeapplied", resourceCulture);
            }
        }
        
        internal static string btnBuyNow {
            get {
                return ResourceManager.GetString("btnBuyNow", resourceCulture);
            }
        }
        
        internal static string btnGotohome {
            get {
                return ResourceManager.GetString("btnGotohome", resourceCulture);
            }
        }
        
        internal static string lblLogoutmessage {
            get {
                return ResourceManager.GetString("lblLogoutmessage", resourceCulture);
            }
        }
        
        internal static string titleMyOrders {
            get {
                return ResourceManager.GetString("titleMyOrders", resourceCulture);
            }
        }
        
        internal static string lblOrderon {
            get {
                return ResourceManager.GetString("lblOrderon", resourceCulture);
            }
        }
        
        internal static string lblPlacedon {
            get {
                return ResourceManager.GetString("lblPlacedon", resourceCulture);
            }
        }
        
        internal static string lblQuantity {
            get {
                return ResourceManager.GetString("lblQuantity", resourceCulture);
            }
        }
        
        internal static string lblperitem {
            get {
                return ResourceManager.GetString("lblperitem", resourceCulture);
            }
        }
        
        internal static string btnReturnOrder {
            get {
                return ResourceManager.GetString("btnReturnOrder", resourceCulture);
            }
        }
        
        internal static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        internal static string btnViewDetails {
            get {
                return ResourceManager.GetString("btnViewDetails", resourceCulture);
            }
        }
        
        internal static string titleUpdatePassword {
            get {
                return ResourceManager.GetString("titleUpdatePassword", resourceCulture);
            }
        }
        
        internal static string lblFullName {
            get {
                return ResourceManager.GetString("lblFullName", resourceCulture);
            }
        }
        
        internal static string lblEmailorMobileNo {
            get {
                return ResourceManager.GetString("lblEmailorMobileNo", resourceCulture);
            }
        }
        
        internal static string btnGetOTP {
            get {
                return ResourceManager.GetString("btnGetOTP", resourceCulture);
            }
        }
        
        internal static string lblWelcometo {
            get {
                return ResourceManager.GetString("lblWelcometo", resourceCulture);
            }
        }
        
        internal static string lblPanasonic {
            get {
                return ResourceManager.GetString("lblPanasonic", resourceCulture);
            }
        }
        
        internal static string lblDashboard {
            get {
                return ResourceManager.GetString("lblDashboard", resourceCulture);
            }
        }
        
        internal static string lblUsernotexist {
            get {
                return ResourceManager.GetString("lblUsernotexist", resourceCulture);
            }
        }
        
        internal static string lblCorrectUserNamePassword {
            get {
                return ResourceManager.GetString("lblCorrectUserNamePassword", resourceCulture);
            }
        }
        
        internal static string lblAlreadyRegistered {
            get {
                return ResourceManager.GetString("lblAlreadyRegistered", resourceCulture);
            }
        }
        
        internal static string lblMobileAlreadyRegistered {
            get {
                return ResourceManager.GetString("lblMobileAlreadyRegistered", resourceCulture);
            }
        }
        
        internal static string lblOTP {
            get {
                return ResourceManager.GetString("lblOTP", resourceCulture);
            }
        }
        
        internal static string lblOTPMessage {
            get {
                return ResourceManager.GetString("lblOTPMessage", resourceCulture);
            }
        }
        
        internal static string lblEmailMobNotExists {
            get {
                return ResourceManager.GetString("lblEmailMobNotExists", resourceCulture);
            }
        }
        
        internal static string lblIncorrectPassword {
            get {
                return ResourceManager.GetString("lblIncorrectPassword", resourceCulture);
            }
        }
        
        internal static string lblPasswordChangedSuccesfully {
            get {
                return ResourceManager.GetString("lblPasswordChangedSuccesfully", resourceCulture);
            }
        }
        
        internal static string lblFailedtochangepassword_ {
            get {
                return ResourceManager.GetString("lblFailedtochangepassword.", resourceCulture);
            }
        }
        
        internal static string lblEnterPassword {
            get {
                return ResourceManager.GetString("lblEnterPassword", resourceCulture);
            }
        }
        
        internal static string lblEnterNewPassword {
            get {
                return ResourceManager.GetString("lblEnterNewPassword", resourceCulture);
            }
        }
        
        internal static string lblConfirmPassword {
            get {
                return ResourceManager.GetString("lblConfirmPassword", resourceCulture);
            }
        }
        
        internal static string lblPasswordNotMatch {
            get {
                return ResourceManager.GetString("lblPasswordNotMatch", resourceCulture);
            }
        }
        
        internal static string lblAPIError {
            get {
                return ResourceManager.GetString("lblAPIError", resourceCulture);
            }
        }
        
        internal static string lblEnteremailormobileno {
            get {
                return ResourceManager.GetString("lblEnteremailormobileno", resourceCulture);
            }
        }
        
        internal static string lblRememberMyPassword {
            get {
                return ResourceManager.GetString("lblRememberMyPassword", resourceCulture);
            }
        }
        
        internal static string lblNotyetregistered {
            get {
                return ResourceManager.GetString("lblNotyetregistered", resourceCulture);
            }
        }
        
        internal static string lblRegisternow {
            get {
                return ResourceManager.GetString("lblRegisternow", resourceCulture);
            }
        }
        
        internal static string lblCheckEnteredEmailMob {
            get {
                return ResourceManager.GetString("lblCheckEnteredEmailMob", resourceCulture);
            }
        }
        
        internal static string lblSelectCountry {
            get {
                return ResourceManager.GetString("lblSelectCountry", resourceCulture);
            }
        }
        
        internal static string lblErrorEmptyPassword {
            get {
                return ResourceManager.GetString("lblErrorEmptyPassword", resourceCulture);
            }
        }
        
        internal static string lblErrorLowerCaseLetter {
            get {
                return ResourceManager.GetString("lblErrorLowerCaseLetter", resourceCulture);
            }
        }
        
        internal static string lblErrorUpperCaseLetter {
            get {
                return ResourceManager.GetString("lblErrorUpperCaseLetter", resourceCulture);
            }
        }
        
        internal static string lblErrorMoreCharacter {
            get {
                return ResourceManager.GetString("lblErrorMoreCharacter", resourceCulture);
            }
        }
        
        internal static string lblErrorNumericValue {
            get {
                return ResourceManager.GetString("lblErrorNumericValue", resourceCulture);
            }
        }
        
        internal static string lblErrorSpecialCharacter {
            get {
                return ResourceManager.GetString("lblErrorSpecialCharacter", resourceCulture);
            }
        }
        
        internal static string lblEnterOTP {
            get {
                return ResourceManager.GetString("lblEnterOTP", resourceCulture);
            }
        }
        
        internal static string lblNewOTP {
            get {
                return ResourceManager.GetString("lblNewOTP", resourceCulture);
            }
        }
        
        internal static string lblErrorGPS {
            get {
                return ResourceManager.GetString("lblErrorGPS", resourceCulture);
            }
        }
        
        internal static string lblCartEmpty {
            get {
                return ResourceManager.GetString("lblCartEmpty", resourceCulture);
            }
        }
        
        internal static string lblEnterPromoCode {
            get {
                return ResourceManager.GetString("lblEnterPromoCode", resourceCulture);
            }
        }
        
        internal static string lblValidPromoCode {
            get {
                return ResourceManager.GetString("lblValidPromoCode", resourceCulture);
            }
        }
        
        internal static string lblSelectTandC {
            get {
                return ResourceManager.GetString("lblSelectTandC", resourceCulture);
            }
        }
        
        internal static string lblSeller {
            get {
                return ResourceManager.GetString("lblSeller", resourceCulture);
            }
        }
        
        internal static string lblPKR {
            get {
                return ResourceManager.GetString("lblPKR", resourceCulture);
            }
        }
        
        internal static string lblDeliveredIn {
            get {
                return ResourceManager.GetString("lblDeliveredIn", resourceCulture);
            }
        }
        
        internal static string lblPaymentMode {
            get {
                return ResourceManager.GetString("lblPaymentMode", resourceCulture);
            }
        }
        
        internal static string lblCOD {
            get {
                return ResourceManager.GetString("lblCOD", resourceCulture);
            }
        }
        
        internal static string lblAddtocart {
            get {
                return ResourceManager.GetString("lblAddtocart", resourceCulture);
            }
        }
        
        internal static string lblBuyNow {
            get {
                return ResourceManager.GetString("lblBuyNow", resourceCulture);
            }
        }
        
        internal static string lblStandbysetrequest {
            get {
                return ResourceManager.GetString("lblStandbysetrequest", resourceCulture);
            }
        }
        
        internal static string lblMore {
            get {
                return ResourceManager.GetString("lblMore", resourceCulture);
            }
        }
        
        internal static string lblRate {
            get {
                return ResourceManager.GetString("lblRate", resourceCulture);
            }
        }
        
        internal static string lblPleaseenterdescription {
            get {
                return ResourceManager.GetString("lblPleaseenterdescription", resourceCulture);
            }
        }
        
        internal static string lblErrorSelectServiceCenter {
            get {
                return ResourceManager.GetString("lblErrorSelectServiceCenter", resourceCulture);
            }
        }
        
        internal static string lblErrorSelectAMCType {
            get {
                return ResourceManager.GetString("lblErrorSelectAMCType", resourceCulture);
            }
        }
        
        internal static string lblSelectServiceCentor {
            get {
                return ResourceManager.GetString("lblSelectServiceCentor", resourceCulture);
            }
        }
        
        internal static string titleAMCRequest {
            get {
                return ResourceManager.GetString("titleAMCRequest", resourceCulture);
            }
        }
        
        internal static string lblServiceCenter {
            get {
                return ResourceManager.GetString("lblServiceCenter", resourceCulture);
            }
        }
        
        internal static string lblOnlyService {
            get {
                return ResourceManager.GetString("lblOnlyService", resourceCulture);
            }
        }
        
        internal static string lblPartsandService {
            get {
                return ResourceManager.GetString("lblPartsandService", resourceCulture);
            }
        }
        
        internal static string lblAMCType {
            get {
                return ResourceManager.GetString("lblAMCType", resourceCulture);
            }
        }
        
        internal static string lblMonths {
            get {
                return ResourceManager.GetString("lblMonths", resourceCulture);
            }
        }
        
        internal static string lblAED {
            get {
                return ResourceManager.GetString("lblAED", resourceCulture);
            }
        }
        
        internal static string lblApply {
            get {
                return ResourceManager.GetString("lblApply", resourceCulture);
            }
        }
        
        internal static string lblSendRequest {
            get {
                return ResourceManager.GetString("lblSendRequest", resourceCulture);
            }
        }
        
        internal static string lblSelectSeller {
            get {
                return ResourceManager.GetString("lblSelectSeller", resourceCulture);
            }
        }
        
        internal static string lblNoaccessoriesavailable {
            get {
                return ResourceManager.GetString("lblNoaccessoriesavailable", resourceCulture);
            }
        }
        
        internal static string lblStock {
            get {
                return ResourceManager.GetString("lblStock", resourceCulture);
            }
        }
        
        internal static string titleShoppingCart {
            get {
                return ResourceManager.GetString("titleShoppingCart", resourceCulture);
            }
        }
        
        internal static string lblTotalAmount {
            get {
                return ResourceManager.GetString("lblTotalAmount", resourceCulture);
            }
        }
        
        internal static string lblCheckout {
            get {
                return ResourceManager.GetString("lblCheckout", resourceCulture);
            }
        }
        
        internal static string lblInclusivetax {
            get {
                return ResourceManager.GetString("lblInclusivetax", resourceCulture);
            }
        }
        
        internal static string lblPlaceOrder {
            get {
                return ResourceManager.GetString("lblPlaceOrder", resourceCulture);
            }
        }
        
        internal static string lblNoRecords {
            get {
                return ResourceManager.GetString("lblNoRecords", resourceCulture);
            }
        }
        
        internal static string lblOrderno {
            get {
                return ResourceManager.GetString("lblOrderno", resourceCulture);
            }
        }
        
        internal static string titleOrderDetails {
            get {
                return ResourceManager.GetString("titleOrderDetails", resourceCulture);
            }
        }
        
        internal static string lblReturnFullOrder {
            get {
                return ResourceManager.GetString("lblReturnFullOrder", resourceCulture);
            }
        }
        
        internal static string lblShippingAddress {
            get {
                return ResourceManager.GetString("lblShippingAddress", resourceCulture);
            }
        }
        
        internal static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        internal static string titleReturnProduct {
            get {
                return ResourceManager.GetString("titleReturnProduct", resourceCulture);
            }
        }
        
        internal static string lblReturn {
            get {
                return ResourceManager.GetString("lblReturn", resourceCulture);
            }
        }
        
        internal static string lblPickAddress {
            get {
                return ResourceManager.GetString("lblPickAddress", resourceCulture);
            }
        }
        
        internal static string lblContinue {
            get {
                return ResourceManager.GetString("lblContinue", resourceCulture);
            }
        }
        
        internal static string titleAMCRequestHistory {
            get {
                return ResourceManager.GetString("titleAMCRequestHistory", resourceCulture);
            }
        }
        
        internal static string lblAMCTypeNm {
            get {
                return ResourceManager.GetString("lblAMCTypeNm", resourceCulture);
            }
        }
        
        internal static string lblProductName {
            get {
                return ResourceManager.GetString("lblProductName", resourceCulture);
            }
        }
        
        internal static string lblByproceedingyouagreetothe {
            get {
                return ResourceManager.GetString("lblByproceedingyouagreetothe", resourceCulture);
            }
        }
        
        internal static string lblTermsofservice {
            get {
                return ResourceManager.GetString("lblTermsofservice", resourceCulture);
            }
        }
        
        internal static string lblPrivacypolicy {
            get {
                return ResourceManager.GetString("lblPrivacypolicy", resourceCulture);
            }
        }
        
        internal static string lblProceed {
            get {
                return ResourceManager.GetString("lblProceed", resourceCulture);
            }
        }
        
        internal static string lblAlreadyhaveanAccount {
            get {
                return ResourceManager.GetString("lblAlreadyhaveanAccount", resourceCulture);
            }
        }
        
        internal static string lblPrimaryAddress {
            get {
                return ResourceManager.GetString("lblPrimaryAddress", resourceCulture);
            }
        }
        
        internal static string lblApartmentHuseNo {
            get {
                return ResourceManager.GetString("lblApartmentHuseNo", resourceCulture);
            }
        }
        
        internal static string lblBuildingVillaName {
            get {
                return ResourceManager.GetString("lblBuildingVillaName", resourceCulture);
            }
        }
        
        internal static string lblArea {
            get {
                return ResourceManager.GetString("lblArea", resourceCulture);
            }
        }
        
        internal static string lblSkip {
            get {
                return ResourceManager.GetString("lblSkip", resourceCulture);
            }
        }
        
        internal static string lblVerifyRegistration {
            get {
                return ResourceManager.GetString("lblVerifyRegistration", resourceCulture);
            }
        }
        
        internal static string lblverify {
            get {
                return ResourceManager.GetString("lblverify", resourceCulture);
            }
        }
        
        internal static string lblErrorNotReceivedOTP {
            get {
                return ResourceManager.GetString("lblErrorNotReceivedOTP", resourceCulture);
            }
        }
        
        internal static string lblResend {
            get {
                return ResourceManager.GetString("lblResend", resourceCulture);
            }
        }
        
        internal static string lblAgreed {
            get {
                return ResourceManager.GetString("lblAgreed", resourceCulture);
            }
        }
        
        internal static string lblUpdateAddress {
            get {
                return ResourceManager.GetString("lblUpdateAddress", resourceCulture);
            }
        }
        
        internal static string lblEnterBuildingName {
            get {
                return ResourceManager.GetString("lblEnterBuildingName", resourceCulture);
            }
        }
        
        internal static string lblEnterArea {
            get {
                return ResourceManager.GetString("lblEnterArea", resourceCulture);
            }
        }
        
        internal static string lblEnterCity {
            get {
                return ResourceManager.GetString("lblEnterCity", resourceCulture);
            }
        }
        
        internal static string lblEnterState {
            get {
                return ResourceManager.GetString("lblEnterState", resourceCulture);
            }
        }
        
        internal static string lblEnterComments {
            get {
                return ResourceManager.GetString("lblEnterComments", resourceCulture);
            }
        }
        
        internal static string lblEnterOtherMessage {
            get {
                return ResourceManager.GetString("lblEnterOtherMessage", resourceCulture);
            }
        }
        
        internal static string lblEnterModelNumber {
            get {
                return ResourceManager.GetString("lblEnterModelNumber", resourceCulture);
            }
        }
        
        internal static string lblEnterSerialNumber {
            get {
                return ResourceManager.GetString("lblEnterSerialNumber", resourceCulture);
            }
        }
        
        internal static string lblSelectPurchaseDate {
            get {
                return ResourceManager.GetString("lblSelectPurchaseDate", resourceCulture);
            }
        }
        
        internal static string lblErrorSelectCountry {
            get {
                return ResourceManager.GetString("lblErrorSelectCountry", resourceCulture);
            }
        }
        
        internal static string lblErrorUploadPurchanseInvoice {
            get {
                return ResourceManager.GetString("lblErrorUploadPurchanseInvoice", resourceCulture);
            }
        }
        
        internal static string lblErrorEnterDealerName {
            get {
                return ResourceManager.GetString("lblErrorEnterDealerName", resourceCulture);
            }
        }
        
        internal static string lblErrorEnterDealerAddress {
            get {
                return ResourceManager.GetString("lblErrorEnterDealerAddress", resourceCulture);
            }
        }
        
        internal static string lblPhotoUpload {
            get {
                return ResourceManager.GetString("lblPhotoUpload", resourceCulture);
            }
        }
        
        internal static string lblTakePhoto {
            get {
                return ResourceManager.GetString("lblTakePhoto", resourceCulture);
            }
        }
        
        internal static string lblGallery {
            get {
                return ResourceManager.GetString("lblGallery", resourceCulture);
            }
        }
        
        internal static string lblErrorCameranotsupported {
            get {
                return ResourceManager.GetString("lblErrorCameranotsupported", resourceCulture);
            }
        }
        
        internal static string lblError {
            get {
                return ResourceManager.GetString("lblError", resourceCulture);
            }
        }
        
        internal static string lblConfirmation {
            get {
                return ResourceManager.GetString("lblConfirmation", resourceCulture);
            }
        }
        
        internal static string lblDoYouWantToDelete {
            get {
                return ResourceManager.GetString("lblDoYouWantToDelete", resourceCulture);
            }
        }
        
        internal static string lblProductDetailsDeleted {
            get {
                return ResourceManager.GetString("lblProductDetailsDeleted", resourceCulture);
            }
        }
        
        internal static string lblSuccess {
            get {
                return ResourceManager.GetString("lblSuccess", resourceCulture);
            }
        }
        
        internal static string lblWarrantycarddownloaded {
            get {
                return ResourceManager.GetString("lblWarrantycarddownloaded", resourceCulture);
            }
        }
        
        internal static string lblYourwarrantycardnotyetready {
            get {
                return ResourceManager.GetString("lblYourwarrantycardnotyetready", resourceCulture);
            }
        }
        
        internal static string lblPleaseEnterNewPassword {
            get {
                return ResourceManager.GetString("lblPleaseEnterNewPassword", resourceCulture);
            }
        }
        
        internal static string lblEnterFollowupMsg {
            get {
                return ResourceManager.GetString("lblEnterFollowupMsg", resourceCulture);
            }
        }
        
        internal static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
        
        internal static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        internal static string lblUpdated {
            get {
                return ResourceManager.GetString("lblUpdated", resourceCulture);
            }
        }
        
        internal static string lblNotWorking {
            get {
                return ResourceManager.GetString("lblNotWorking", resourceCulture);
            }
        }
        
        internal static string lblPartiallyworking {
            get {
                return ResourceManager.GetString("lblPartiallyworking", resourceCulture);
            }
        }
        
        internal static string lblWorkingbutotherissues {
            get {
                return ResourceManager.GetString("lblWorkingbutotherissues", resourceCulture);
            }
        }
        
        internal static string lblPleaseselectdate {
            get {
                return ResourceManager.GetString("lblPleaseselectdate", resourceCulture);
            }
        }
        
        internal static string lblPleaseselecttime {
            get {
                return ResourceManager.GetString("lblPleaseselecttime", resourceCulture);
            }
        }
        
        internal static string lblServicerequestupdatedSuccessfully {
            get {
                return ResourceManager.GetString("lblServicerequestupdatedSuccessfully", resourceCulture);
            }
        }
        
        internal static string lblServiceRequestClosed {
            get {
                return ResourceManager.GetString("lblServiceRequestClosed", resourceCulture);
            }
        }
        
        internal static string lblErrorCheckInternet {
            get {
                return ResourceManager.GetString("lblErrorCheckInternet", resourceCulture);
            }
        }
        
        internal static string lblErrorAlert {
            get {
                return ResourceManager.GetString("lblErrorAlert", resourceCulture);
            }
        }
        
        internal static string lblProductRegSuccessMsg {
            get {
                return ResourceManager.GetString("lblProductRegSuccessMsg", resourceCulture);
            }
        }
        
        internal static string lblCongratulations {
            get {
                return ResourceManager.GetString("lblCongratulations", resourceCulture);
            }
        }
        
        internal static string lblGotoMyProducts {
            get {
                return ResourceManager.GetString("lblGotoMyProducts", resourceCulture);
            }
        }
        
        internal static string lblSRDetails {
            get {
                return ResourceManager.GetString("lblSRDetails", resourceCulture);
            }
        }
        
        internal static string lblFollowUp {
            get {
                return ResourceManager.GetString("lblFollowUp", resourceCulture);
            }
        }
        
        internal static string lblPleaseContactAdmin {
            get {
                return ResourceManager.GetString("lblPleaseContactAdmin", resourceCulture);
            }
        }
        
        internal static string lblProductModelNumber {
            get {
                return ResourceManager.GetString("lblProductModelNumber", resourceCulture);
            }
        }
        
        internal static string lblServiceRequestType {
            get {
                return ResourceManager.GetString("lblServiceRequestType", resourceCulture);
            }
        }
        
        internal static string lblServiceLocation {
            get {
                return ResourceManager.GetString("lblServiceLocation", resourceCulture);
            }
        }
        
        internal static string lblVisitchargesareapplicable {
            get {
                return ResourceManager.GetString("lblVisitchargesareapplicable", resourceCulture);
            }
        }
        
        internal static string lblUploadProductPhoto {
            get {
                return ResourceManager.GetString("lblUploadProductPhoto", resourceCulture);
            }
        }
        
        internal static string lblPleaseselectservicerequesttype {
            get {
                return ResourceManager.GetString("lblPleaseselectservicerequesttype", resourceCulture);
            }
        }
        
        internal static string lblPleaseenteralternatenumber {
            get {
                return ResourceManager.GetString("lblPleaseenteralternatenumber", resourceCulture);
            }
        }
        
        internal static string lblPleaseselectaddresstosubmit {
            get {
                return ResourceManager.GetString("lblPleaseselectaddresstosubmit", resourceCulture);
            }
        }
        
        internal static string lblAMCRequestMessage {
            get {
                return ResourceManager.GetString("lblAMCRequestMessage", resourceCulture);
            }
        }
        
        internal static string lblGotoAMCHistory {
            get {
                return ResourceManager.GetString("lblGotoAMCHistory", resourceCulture);
            }
        }
        
        internal static string msgAddressupdated {
            get {
                return ResourceManager.GetString("msgAddressupdated", resourceCulture);
            }
        }
        
        internal static string msgAddresscreated {
            get {
                return ResourceManager.GetString("msgAddresscreated", resourceCulture);
            }
        }
        
        internal static string msgAMCRequestcreatedsuccessfully {
            get {
                return ResourceManager.GetString("msgAMCRequestcreatedsuccessfully", resourceCulture);
            }
        }
        
        internal static string msgYourinquirysubmittedsuccessfully {
            get {
                return ResourceManager.GetString("msgYourinquirysubmittedsuccessfully", resourceCulture);
            }
        }
        
        internal static string msgFeedbacksubmittedSuccessfully {
            get {
                return ResourceManager.GetString("msgFeedbacksubmittedSuccessfully", resourceCulture);
            }
        }
        
        internal static string msgInvalidloginattempt {
            get {
                return ResourceManager.GetString("msgInvalidloginattempt", resourceCulture);
            }
        }
        
        internal static string msgYourpasswordisincorrect {
            get {
                return ResourceManager.GetString("msgYourpasswordisincorrect", resourceCulture);
            }
        }
        
        internal static string msgUpdatetheapp {
            get {
                return ResourceManager.GetString("msgUpdatetheapp", resourceCulture);
            }
        }
        
        internal static string msgPleaseentercorrectusernameandpassword {
            get {
                return ResourceManager.GetString("msgPleaseentercorrectusernameandpassword", resourceCulture);
            }
        }
        
        internal static string msgEmailalreadyregistered {
            get {
                return ResourceManager.GetString("msgEmailalreadyregistered", resourceCulture);
            }
        }
        
        internal static string msgMobilenumberalreadyregistered {
            get {
                return ResourceManager.GetString("msgMobilenumberalreadyregistered", resourceCulture);
            }
        }
        
        internal static string msgInvalidusername {
            get {
                return ResourceManager.GetString("msgInvalidusername", resourceCulture);
            }
        }
        
        internal static string msgUserwiththeentereddetailsdoesnotexists {
            get {
                return ResourceManager.GetString("msgUserwiththeentereddetailsdoesnotexists", resourceCulture);
            }
        }
        
        internal static string msgOTPhasbeensenttoenteredEmailorMobile {
            get {
                return ResourceManager.GetString("msgOTPhasbeensenttoenteredEmailorMobile", resourceCulture);
            }
        }
        
        internal static string msgEnteredcurrentpasswordisincorrect {
            get {
                return ResourceManager.GetString("msgEnteredcurrentpasswordisincorrect", resourceCulture);
            }
        }
        
        internal static string msgPasswordchangedsuccessfully {
            get {
                return ResourceManager.GetString("msgPasswordchangedsuccessfully", resourceCulture);
            }
        }
        
        internal static string msgFailedtochangepassword {
            get {
                return ResourceManager.GetString("msgFailedtochangepassword", resourceCulture);
            }
        }
        
        internal static string msgNewOTPCreated {
            get {
                return ResourceManager.GetString("msgNewOTPCreated", resourceCulture);
            }
        }
        
        internal static string msgOrderplacedsuccessfully {
            get {
                return ResourceManager.GetString("msgOrderplacedsuccessfully", resourceCulture);
            }
        }
        
        internal static string msgOrderreturnrequestsubmittedsuccessfully {
            get {
                return ResourceManager.GetString("msgOrderreturnrequestsubmittedsuccessfully", resourceCulture);
            }
        }
        
        internal static string msgFullOrderreturnrequestubmittedsuccessfully {
            get {
                return ResourceManager.GetString("msgFullOrderreturnrequestubmittedsuccessfully", resourceCulture);
            }
        }
        
        internal static string msgSparepartrequestsubmitted {
            get {
                return ResourceManager.GetString("msgSparepartrequestsubmitted", resourceCulture);
            }
        }
        
        internal static string msgProfileupdatedsuccessfully {
            get {
                return ResourceManager.GetString("msgProfileupdatedsuccessfully", resourceCulture);
            }
        }
        
        internal static string msgProductisalreadyregistered {
            get {
                return ResourceManager.GetString("msgProductisalreadyregistered", resourceCulture);
            }
        }
        
        internal static string msgProductregisteredsuccessfully {
            get {
                return ResourceManager.GetString("msgProductregisteredsuccessfully", resourceCulture);
            }
        }
        
        internal static string msgProductnotsaved {
            get {
                return ResourceManager.GetString("msgProductnotsaved", resourceCulture);
            }
        }
        
        internal static string msgThankyoufortakingpartinsurvey {
            get {
                return ResourceManager.GetString("msgThankyoufortakingpartinsurvey", resourceCulture);
            }
        }
        
        internal static string msgServicerequestupdatedSuccessfully {
            get {
                return ResourceManager.GetString("msgServicerequestupdatedSuccessfully", resourceCulture);
            }
        }
        
        internal static string msgPromocodeAppliedSuccessfully {
            get {
                return ResourceManager.GetString("msgPromocodeAppliedSuccessfully", resourceCulture);
            }
        }
        
        internal static string msgErrorinapplyingPromoCode {
            get {
                return ResourceManager.GetString("msgErrorinapplyingPromoCode", resourceCulture);
            }
        }
        
        internal static string msgStandbysetrequestalreadyexists {
            get {
                return ResourceManager.GetString("msgStandbysetrequestalreadyexists", resourceCulture);
            }
        }
        
        internal static string msgStandbysetrequestcreatedsuccessfully {
            get {
                return ResourceManager.GetString("msgStandbysetrequestcreatedsuccessfully", resourceCulture);
            }
        }
        
        internal static string msgInvoicegeneratedsuccesfully {
            get {
                return ResourceManager.GetString("msgInvoicegeneratedsuccesfully", resourceCulture);
            }
        }
        
        internal static string msgYouhavealreadyparticipatedinsurvey {
            get {
                return ResourceManager.GetString("msgYouhavealreadyparticipatedinsurvey", resourceCulture);
            }
        }
        
        internal static string msgNopromotionavailable {
            get {
                return ResourceManager.GetString("msgNopromotionavailable", resourceCulture);
            }
        }
        
        internal static string msgparticipatinginsurvey {
            get {
                return ResourceManager.GetString("msgparticipatinginsurvey", resourceCulture);
            }
        }
        
        internal static string msgInquiry {
            get {
                return ResourceManager.GetString("msgInquiry", resourceCulture);
            }
        }
        
        internal static string msgNotedQuery {
            get {
                return ResourceManager.GetString("msgNotedQuery", resourceCulture);
            }
        }
        
        internal static string msgThankyouforyourfeedback {
            get {
                return ResourceManager.GetString("msgThankyouforyourfeedback", resourceCulture);
            }
        }
        
        internal static string msgAMCrequestsentsuccessfully {
            get {
                return ResourceManager.GetString("msgAMCrequestsentsuccessfully", resourceCulture);
            }
        }
        
        internal static string msgOrderreturnedsuccessfully {
            get {
                return ResourceManager.GetString("msgOrderreturnedsuccessfully", resourceCulture);
            }
        }
        
        internal static string lblHello {
            get {
                return ResourceManager.GetString("lblHello", resourceCulture);
            }
        }
        
        internal static string msgLocationNotProvide {
            get {
                return ResourceManager.GetString("msgLocationNotProvide", resourceCulture);
            }
        }
        
        internal static string lblErrorEnableGPS {
            get {
                return ResourceManager.GetString("lblErrorEnableGPS", resourceCulture);
            }
        }
        
        internal static string msgServicerequestisalreadyinprogress {
            get {
                return ResourceManager.GetString("msgServicerequestisalreadyinprogress", resourceCulture);
            }
        }
        
        internal static string lblGotoServiceRequests {
            get {
                return ResourceManager.GetString("lblGotoServiceRequests", resourceCulture);
            }
        }
        
        internal static string titleIwilltakemyproducttoservicecenter {
            get {
                return ResourceManager.GetString("titleIwilltakemyproducttoservicecenter", resourceCulture);
            }
        }
        
        internal static string titleIPreferHomeService {
            get {
                return ResourceManager.GetString("titleIPreferHomeService", resourceCulture);
            }
        }
        
        internal static string lblErrorIncorrectToken {
            get {
                return ResourceManager.GetString("lblErrorIncorrectToken", resourceCulture);
            }
        }
        
        internal static string lblErrorFailedReturnOrder {
            get {
                return ResourceManager.GetString("lblErrorFailedReturnOrder", resourceCulture);
            }
        }
        
        internal static string lblOthers {
            get {
                return ResourceManager.GetString("lblOthers", resourceCulture);
            }
        }
        
        internal static string lblEnteryourqueryrequest {
            get {
                return ResourceManager.GetString("lblEnteryourqueryrequest", resourceCulture);
            }
        }
        
        internal static string lblPleaseEnteryourqueryrequest {
            get {
                return ResourceManager.GetString("lblPleaseEnteryourqueryrequest", resourceCulture);
            }
        }
        
        internal static string lblThankYouForVIsitingUs {
            get {
                return ResourceManager.GetString("lblThankYouForVIsitingUs", resourceCulture);
            }
        }
        
        internal static string lblPleaseTellUsMoreInDetail {
            get {
                return ResourceManager.GetString("lblPleaseTellUsMoreInDetail", resourceCulture);
            }
        }
        
        internal static string titleNotifications {
            get {
                return ResourceManager.GetString("titleNotifications", resourceCulture);
            }
        }
        
        internal static string lblNoNotifications {
            get {
                return ResourceManager.GetString("lblNoNotifications", resourceCulture);
            }
        }
        
        internal static string lblDomestic {
            get {
                return ResourceManager.GetString("lblDomestic", resourceCulture);
            }
        }
        
        internal static string lblExtended {
            get {
                return ResourceManager.GetString("lblExtended", resourceCulture);
            }
        }
        
        internal static string lblInternational {
            get {
                return ResourceManager.GetString("lblInternational", resourceCulture);
            }
        }
        
        internal static string lblOutwarranty {
            get {
                return ResourceManager.GetString("lblOutwarranty", resourceCulture);
            }
        }
        
        internal static string lblAwaitingconfirmation {
            get {
                return ResourceManager.GetString("lblAwaitingconfirmation", resourceCulture);
            }
        }
        
        internal static string lblAll {
            get {
                return ResourceManager.GetString("lblAll", resourceCulture);
            }
        }
        
        internal static string lblCurrency {
            get {
                return ResourceManager.GetString("lblCurrency", resourceCulture);
            }
        }
        
        internal static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        internal static string lblTrack {
            get {
                return ResourceManager.GetString("lblTrack", resourceCulture);
            }
        }
        
        internal static string lblOrderTracking {
            get {
                return ResourceManager.GetString("lblOrderTracking", resourceCulture);
            }
        }
        
        internal static string lblCostEstimation {
            get {
                return ResourceManager.GetString("lblCostEstimation", resourceCulture);
            }
        }
        
        internal static string lblNoCostEstimation {
            get {
                return ResourceManager.GetString("lblNoCostEstimation", resourceCulture);
            }
        }
        
        internal static string lblEstimationDate {
            get {
                return ResourceManager.GetString("lblEstimationDate", resourceCulture);
            }
        }
        
        internal static string lblApprovalDate {
            get {
                return ResourceManager.GetString("lblApprovalDate", resourceCulture);
            }
        }
        
        internal static string lblEstimationStatus {
            get {
                return ResourceManager.GetString("lblEstimationStatus", resourceCulture);
            }
        }
        
        internal static string lblView {
            get {
                return ResourceManager.GetString("lblView", resourceCulture);
            }
        }
        
        internal static string lblGoToProducts {
            get {
                return ResourceManager.GetString("lblGoToProducts", resourceCulture);
            }
        }
        
        internal static string lblPostalCode {
            get {
                return ResourceManager.GetString("lblPostalCode", resourceCulture);
            }
        }
        
        internal static string lblOTPVerificationMsg {
            get {
                return ResourceManager.GetString("lblOTPVerificationMsg", resourceCulture);
            }
        }
        
        internal static string SparePartSuccessMsg {
            get {
                return ResourceManager.GetString("SparePartSuccessMsg", resourceCulture);
            }
        }
        
        internal static string lblNumOfYear {
            get {
                return ResourceManager.GetString("lblNumOfYear", resourceCulture);
            }
        }
        
        internal static string lblNumOfYear1 {
            get {
                return ResourceManager.GetString("lblNumOfYear1", resourceCulture);
            }
        }
        
        internal static string lblContractDuration {
            get {
                return ResourceManager.GetString("lblContractDuration", resourceCulture);
            }
        }
        
        internal static string lblCustName {
            get {
                return ResourceManager.GetString("lblCustName", resourceCulture);
            }
        }
        
        internal static string lblDiscountAmount {
            get {
                return ResourceManager.GetString("lblDiscountAmount", resourceCulture);
            }
        }
        
        internal static string lblTaxName {
            get {
                return ResourceManager.GetString("lblTaxName", resourceCulture);
            }
        }
        
        internal static string ErrorMsgMobilenumberisnotavailable {
            get {
                return ResourceManager.GetString("ErrorMsgMobilenumberisnotavailable", resourceCulture);
            }
        }
        
        internal static string lblServiceCharges {
            get {
                return ResourceManager.GetString("lblServiceCharges", resourceCulture);
            }
        }
        
        internal static string lblPartCharges {
            get {
                return ResourceManager.GetString("lblPartCharges", resourceCulture);
            }
        }
        
        internal static string lblPartNumber {
            get {
                return ResourceManager.GetString("lblPartNumber", resourceCulture);
            }
        }
        
        internal static string lblApproved {
            get {
                return ResourceManager.GetString("lblApproved", resourceCulture);
            }
        }
        
        internal static string lblPending {
            get {
                return ResourceManager.GetString("lblPending", resourceCulture);
            }
        }
        
        internal static string lblAMCTypeNotAvailable {
            get {
                return ResourceManager.GetString("lblAMCTypeNotAvailable", resourceCulture);
            }
        }
        
        internal static string lblqty {
            get {
                return ResourceManager.GetString("lblqty", resourceCulture);
            }
        }
        
        internal static string lblRepair {
            get {
                return ResourceManager.GetString("lblRepair", resourceCulture);
            }
        }
        
        internal static string lblPromoCodeDiscount {
            get {
                return ResourceManager.GetString("lblPromoCodeDiscount", resourceCulture);
            }
        }
        
        internal static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        internal static string lblCreationDate {
            get {
                return ResourceManager.GetString("lblCreationDate", resourceCulture);
            }
        }
        
        internal static string lblAnnouncementDate {
            get {
                return ResourceManager.GetString("lblAnnouncementDate", resourceCulture);
            }
        }
        
        internal static string lblStartDate {
            get {
                return ResourceManager.GetString("lblStartDate", resourceCulture);
            }
        }
        
        internal static string lblExpiryDate {
            get {
                return ResourceManager.GetString("lblExpiryDate", resourceCulture);
            }
        }
        
        internal static string lblRegister {
            get {
                return ResourceManager.GetString("lblRegister", resourceCulture);
            }
        }
        
        internal static string msgCheckInternetConnectivity {
            get {
                return ResourceManager.GetString("msgCheckInternetConnectivity", resourceCulture);
            }
        }
    }
}
